export const ADD_CARD_TO_FORM = "ADD_CARD_TO_FORM";
export const COPY_CARD_TO_FORM = "COPY_CARD_TO_FORM";
export const DELETE_CARD_FROM_FORM = "DELETE_CARD_FROM_FORM";

export const SET_CARD_TITLE = "SET_CARD_TITLE";
export const RESET_CARD_TITLE = "RESET_CARD_TITLE";

export const SET_CARD_TYPE = "SET_CARD_TYPE";
export const RESET_CARD_TYPE = "RESET_CARD_TYPE";

export const SET_SEL_CARD_IND = "SET_SEL_CARD_IND";
export const RESET_SEL_CARD_IND = "RESET_SEL_CARD_IND";

export const ADD_OPT_MULT_CHOICE = "ADD_OPT_MULT_CHOICE";
export const ADD_OTHER_OPT_MULT_CHOICE = "ADD_OTHER_OPT_MULT_CHOICE";
export const UPDATE_OPT_MULT_CHOICE = "UPDATE_OPT_MULT_CHOICE";
export const REMOVE_OPT_MULT_CHOICE = "REMOVE_OPT_MULT_CHOICE";

export const ADD_OPT_MULT_TABLE = "ADD_OPT_MULT_TABLE";
export const UPD_OPT_MULT_TABLE_ROW = "UPD_OPT_MULT_TABLE_ROW";
export const UPD_OPT_MULT_TABLE_COL = "UPD_OPT_MULT_TABLE_COL";
export const REMOVE_OPT_MULT_TABLE_ROW = "REMOVE_OPT_MULT_TABLE_ROW";
export const REMOVE_OPT_MULT_TABLE_COL = "REMOVE_OPT_MULT_TABLE_COL";

export const UPD_LINEAR_SCALE = "UPD_LINEAR_SCALE";
